[package]
name = "Movemate"
version = "1.7.0"
authors = ["David Lucid <david@pentagon.xyz>"]

[addresses]
movemate = "0x7a5fd49ad5d7e7b8e4611a3876d73a55868a4ad9"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
# devnet-0.19.0
rev = "a8af20d94e951ecfb6d0cd47c23cf6393013d8a8"
