[package]
name = "Movemate"
version = "1.5.0"
authors = ["David Lucid <david@pentagon.xyz>"]

[addresses]
movemate = "0x0"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
# devnet-0.18.0
rev = "21fcff72bef3b12f600da861b7708ca5f30d9512"
