[package]
name = "Movemate"
version = "1.2.0"
authors = ["David Lucid <david@pentagon.xyz>"]

[addresses]
std = "0x1"
sui = "0x2"
movemate = "0x0"

[dependencies.MoveStdlib]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/deps/move-stdlib"
# devnet-0.14.0
rev = "2a9ad74262554d2c753d6eaaa057d6612eab8678"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
# devnet-0.14.0
rev = "2a9ad74262554d2c753d6eaaa057d6612eab8678"
